// <auto-generated />
using AcnhApi.DataAccessors.AcnhDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcnhApi.Migrations
{
    [DbContext(typeof(AcnhDbContext))]
    [Migration("20230427211947_DbInit")]
    partial class DbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AcnhApi.DataAccessors.Entities.Fish", b =>
                {
                    b.Property<string>("FishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FishName")
                        .HasColumnType("longtext");

                    b.HasKey("FishId");

                    b.ToTable("Fishes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
